import { IComment, IUser, IVideo } from "types/interfaces";

export const user: IUser = {
  id: 0,
  emailAddress: "test@test.com",
  userName: "test name",
  firstName: "test fname",
  lastName: "test lname",
  profilePicPath: "test pic path",
  password: undefined,
  followers: 1,
  following: 2,
  clipCount: 3,
  likes: 4,
  tagLine: "",
  about: "",
  Followed: false,
  youtube: "",
  twitter: "",
  instagram: "",
  snapChat: "",
  tikTok: "",
  twitch: "",
  verified: false,
  fCMToken: "",
  dtRegistered: "2021-09-14T01:43:25.2489551",
  dtLastLogin: "2021-09-14T01:43:25.2489551",
};

export const comment: IComment = {
  id: "0",
  text: "test comment",
  dtPosted: "2021-09-14T01:43:25.2489551",
  edited: false,
  deleted: false,
  userId: 242,
  user: user,
  profilePic: "pic",
  itemId: "",
  item: undefined,
  likes: 763,
  liked: false,
};

export const video: IVideo = {
  id: "1",
  text: "test video description",
  description: "test video description",
  type: 0,
  videoUrl: "test",
  thumbUrl: "test",
  published: false,
  userId: 0,
  userName: "test user",
  user: user,
  userProfileImagePath: "test",
  dtUploaded: "2021-09-14T01:43:25.2489551",
  dtPublished: "2021-09-14T01:43:25.2489551",
  gameId: 1,
  gameName: "",
  likes: 123,
  views: 321,
  liked: false,
  Comments: [
    { ...comment, id: "1" },
    { ...comment, id: "2" },
  ],
  recorded: false,
};
